:verbose: false
:concurrency: 10
:timeout: 10

:queues:
  - access_log
  - thumb
  - access_log_sum
  - stock
  - tiramon_battle_match_make
  - tiramon_battle
  - tiramon_battle_completer
  - default
